version: "3.3"

services:
  redis:
    image: redis:6.2
    restart: always
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ROOTPASS
  dev:
    image: bitbank-test-dep
    volumes:
      - .:/bitbank/workspace
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: 'postgres://postgres/postgres?user=postgres&password=ROOTPASS'
      CELERY_BROKER_URL: 'redis://redis'
    depends_on:
      - postgres
      - redis
