# Generated by Django 3.2.10 on 2021-12-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='satoshis',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Amount of satoshis owned'),
        ),
    ]
